# Generated by Django 5.2.14 on 2026-05-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_seed_portfolio_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, max_length=600, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
