# Generated by Django 5.2.14 on 2026-05-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_seed_error_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
