# Generated by Django 5.2.14 on 2026-05-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_repo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='languages_used',
            field=models.TextField(blank=True),
        ),
    ]
