from django.db import migrations


GITHUB_PROJECTS = [
    {
        "order": 5,
        "eyebrow": "GitHub",
        "title": "Portfolio",
        "description": "GitHub project for Portfolio, available for review on GitHub.",
        "extra_description": "Stars: 0 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "GitHub project",
        "repo_url": "https://github.com/dragonwolf1o1/Portfolio",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "",
        "is_active": True,
    },
    {
        "order": 6,
        "eyebrow": "GitHub",
        "title": "Movie Rental Analytics",
        "description": "GitHub project for Movie Rental Analytics, available for review on GitHub.",
        "extra_description": "Stars: 0 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Analytics project",
        "repo_url": "https://github.com/dragonwolf1o1/Movie_Rental_Analytics",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "",
        "is_active": True,
    },
    {
        "order": 7,
        "eyebrow": "HTML, Python, CSS, JavaScript, GitHub",
        "title": "Pocket Music",
        "description": "GitHub project for Pocket Music, built around HTML and available for review on GitHub.",
        "extra_description": "Stars: 0 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Web application project",
        "repo_url": "https://github.com/dragonwolf1o1/Pocket_Music",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "HTML, Python, CSS, JavaScript",
        "is_active": True,
    },
    {
        "order": 8,
        "eyebrow": "Python, GitHub",
        "title": "Credit Risk Analysis Scoring System",
        "description": "GitHub project for Credit Risk Analysis Scoring System, built around Python and available for review on GitHub.",
        "extra_description": "Stars: 0 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Analytics project",
        "repo_url": "https://github.com/dragonwolf1o1/Credit-Risk-Analysis-Scoring-System",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "Python",
        "is_active": True,
    },
    {
        "order": 9,
        "eyebrow": "Python, GitHub",
        "title": "Safe Nest Security Api",
        "description": "GitHub project for Safe Nest Security Api, built around Python and available for review on GitHub.",
        "extra_description": "Stars: 0 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Security project",
        "repo_url": "https://github.com/dragonwolf1o1/Safe-Nest-Security-API",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "Python",
        "is_active": True,
    },
    {
        "order": 10,
        "eyebrow": "HTML, CSS, JavaScript, GitHub",
        "title": "E Commerce Site",
        "description": "GitHub project for E Commerce Site, built around HTML and available for review on GitHub.",
        "extra_description": "Stars: 1 | Forks: 1",
        "image_url": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Web application project",
        "repo_url": "https://github.com/dragonwolf1o1/E-Commerce-Site",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "HTML, CSS, JavaScript",
        "is_active": True,
    },
    {
        "order": 11,
        "eyebrow": "PHP, CSS, JavaScript, Fork, GitHub",
        "title": "Bipe Library Managment System",
        "description": "Forked GitHub repository for Bipe Library Managment System, built around PHP and available for review on GitHub.",
        "extra_description": "Forked repository. | Stars: 1 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Database application project",
        "repo_url": "https://github.com/dragonwolf1o1/BIPE_Library_Managment_System",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "PHP, CSS, JavaScript",
        "is_active": True,
    },
    {
        "order": 12,
        "eyebrow": "PHP, CSS, JavaScript, Fork, GitHub",
        "title": "Library Management System Sakshi",
        "description": "Forked GitHub repository for Library Management System Sakshi, built around PHP and available for review on GitHub.",
        "extra_description": "Forked repository. | Stars: 0 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Database application project",
        "repo_url": "https://github.com/dragonwolf1o1/Library-Management-System_Sakshi",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "PHP, CSS, JavaScript",
        "is_active": True,
    },
    {
        "order": 13,
        "eyebrow": "GitHub",
        "title": "Sport Analytics",
        "description": "GitHub project for Sport Analytics, available for review on GitHub.",
        "extra_description": "Stars: 0 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Analytics project",
        "repo_url": "https://github.com/dragonwolf1o1/Sport-Analytics",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "",
        "is_active": True,
    },
    {
        "order": 14,
        "eyebrow": "PHP, CSS, JavaScript, PowerShell, Batchfile, Fork, GitHub",
        "title": "Learn Q",
        "description": "Forked GitHub repository for Learn Q, built around PHP and available for review on GitHub.",
        "extra_description": "Forked repository. | Stars: 0 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "GitHub project",
        "repo_url": "https://github.com/dragonwolf1o1/Learn-Q",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "PHP, CSS, JavaScript, PowerShell, Batchfile",
        "is_active": True,
    },
    {
        "order": 15,
        "eyebrow": "GitHub",
        "title": "Adult Census Income Analysis Power Bi Dashboard",
        "description": "GitHub project for Adult Census Income Analysis Power Bi Dashboard, available for review on GitHub.",
        "extra_description": "Stars: 0 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Analytics project",
        "repo_url": "https://github.com/dragonwolf1o1/Adult_Census_Income_Analysis_Power_BI_Dashboard",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "",
        "is_active": True,
    },
    {
        "order": 16,
        "eyebrow": "Python, HTML, CSS, JavaScript, GitHub",
        "title": "Social Media Plateform",
        "description": "GitHub project for Social Media Plateform, built around Python and available for review on GitHub.",
        "extra_description": "Stars: 0 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Web application project",
        "repo_url": "https://github.com/dragonwolf1o1/Social_Media_Plateform",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "Python, HTML, CSS, JavaScript",
        "is_active": True,
    },
    {
        "order": 17,
        "eyebrow": "HTML, Python, CSS, JavaScript, GitHub",
        "title": "Flexstream",
        "description": "GitHub project for Flexstream, built around HTML and available for review on GitHub.",
        "extra_description": "Stars: 0 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Web application project",
        "repo_url": "https://github.com/dragonwolf1o1/FlexStream",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "HTML, Python, CSS, JavaScript",
        "is_active": True,
    },
    {
        "order": 18,
        "eyebrow": "Python, CSS, HTML, GitHub",
        "title": "Authentication System",
        "description": "GitHub project for Authentication System, built around Python and available for review on GitHub.",
        "extra_description": "Stars: 1 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Database application project",
        "repo_url": "https://github.com/dragonwolf1o1/Authentication-System",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "Python, CSS, HTML",
        "is_active": True,
    },
    {
        "order": 19,
        "eyebrow": "Python, GitHub",
        "title": "Hash Finder",
        "description": "GitHub project for Hash Finder, built around Python and available for review on GitHub.",
        "extra_description": "Stars: 1 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Security project",
        "repo_url": "https://github.com/dragonwolf1o1/Hash-Finder",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "Python",
        "is_active": True,
    },
    {
        "order": 20,
        "eyebrow": "CSS, Python, HTML, GitHub",
        "title": "Customer Details Managment System",
        "description": "GitHub project for Customer Details Managment System, built around CSS and available for review on GitHub.",
        "extra_description": "Stars: 0 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Database application project",
        "repo_url": "https://github.com/dragonwolf1o1/Customer_Details_Managment_System",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "CSS, Python, HTML",
        "is_active": True,
    },
    {
        "order": 21,
        "eyebrow": "Python, CSS, HTML, GitHub",
        "title": "Blog Website Django Framework",
        "description": "GitHub project for Blog Website Django Framework, built around Python and available for review on GitHub.",
        "extra_description": "Stars: 1 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Web application project",
        "repo_url": "https://github.com/dragonwolf1o1/Blog-Website-Django-Framework",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "Python, CSS, HTML",
        "is_active": True,
    },
    {
        "order": 22,
        "eyebrow": "PHP, CSS, JavaScript, Hack, GitHub",
        "title": "Web Bassed Chat Application",
        "description": "GitHub project for Web Bassed Chat Application, built around PHP and available for review on GitHub.",
        "extra_description": "Stars: 1 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Web application project",
        "repo_url": "https://github.com/dragonwolf1o1/Web-Bassed-Chat-Application",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "PHP, CSS, JavaScript, Hack",
        "is_active": True,
    },
    {
        "order": 23,
        "eyebrow": "Python, GitHub",
        "title": "Password Strength Checker",
        "description": "GitHub project for Password Strength Checker, built around Python and available for review on GitHub.",
        "extra_description": "Stars: 1 | Forks: 1",
        "image_url": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Security project",
        "repo_url": "https://github.com/dragonwolf1o1/Password-Strength-Checker",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "Python",
        "is_active": True,
    },
    {
        "order": 24,
        "eyebrow": "Python, GitHub",
        "title": "Hash Verifier",
        "description": "GitHub project for Hash Verifier, built around Python and available for review on GitHub.",
        "extra_description": "Stars: 1 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Security project",
        "repo_url": "https://github.com/dragonwolf1o1/Hash-Verifier",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "Python",
        "is_active": True,
    },
    {
        "order": 25,
        "eyebrow": "Python, GitHub",
        "title": "Banking Managment System",
        "description": "GitHub project for Banking Managment System, built around Python and available for review on GitHub.",
        "extra_description": "Stars: 1 | Forks: 1",
        "image_url": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Database application project",
        "repo_url": "https://github.com/dragonwolf1o1/Banking-Managment-System",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "Python",
        "is_active": True,
    },
    {
        "order": 26,
        "eyebrow": "Python, GitHub",
        "title": "Text Encryption Tool",
        "description": "GitHub project for Text Encryption Tool, built around Python and available for review on GitHub.",
        "extra_description": "Stars: 1 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Security project",
        "repo_url": "https://github.com/dragonwolf1o1/Text-Encryption-Tool",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "Python",
        "is_active": True,
    },
    {
        "order": 27,
        "eyebrow": "Python, GitHub",
        "title": "Internal Network Jammer Using Python",
        "description": "Work only in Linux OSs",
        "extra_description": "Stars: 1 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Security project",
        "repo_url": "https://github.com/dragonwolf1o1/Internal-Network-Jammer-using-Python",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "Python",
        "is_active": True,
    },
    {
        "order": 28,
        "eyebrow": "Python, Shell, Fork, GitHub",
        "title": "Sparrow Wifi",
        "description": "Next-Gen GUI-based WiFi and Bluetooth Analyzer for Linux",
        "extra_description": "Forked repository. | Stars: 0 | Forks: 0",
        "image_url": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1200&auto=format&fit=crop",
        "image_alt": "Security project",
        "repo_url": "https://github.com/dragonwolf1o1/sparrow-wifi",
        "live_url": "",
        "source": "GitHub",
        "languages_used": "Python, Shell",
        "is_active": True,
    },
]


def seed_github_projects(apps, schema_editor):
    Project = apps.get_model("portfolio", "Project")
    ContactDetail = apps.get_model("portfolio", "ContactDetail")

    for project in GITHUB_PROJECTS:
        repo_url = project["repo_url"]
        defaults = project.copy()
        defaults.pop("repo_url")
        Project.objects.update_or_create(repo_url=repo_url, defaults=defaults)

    ContactDetail.objects.update_or_create(
        label="GitHub",
        defaults={
            "value": "github.com/dragonwolf1o1",
            "href": "https://github.com/dragonwolf1o1",
            "order": 5,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_move_profile_image_to_about"),
    ]

    operations = [
        migrations.RunPython(seed_github_projects, migrations.RunPython.noop),
    ]
